### ISSUE TITLE
pygeos error in installation step

### ISSUE THREAD

**Issue by tm-jace-peralta** [thinkingmachines/unicef-ai4d-poverty-mapping#93]
Hello everyone, I'm getting an error in the `make setup` step. It points to a `JSONDecodeError` in the `pygeos` module. Did anyone else encounter this?

> Building wheel for pygeos (pyproject.toml) ... done
  Created wheel for pygeos: filename=pygeos-0.12.0-cp39-cp39-linux_x86_64.whl size=466415 sha256=b5825f6c13d1bcc3f760555744d4aea66940b5b3562ce9f722ecd49b973d7c09
  Stored in directory: /home/jace/.cache/pip/wheels/67/0f/37/46f75689d7cacbc71c82facc1fa05b4e9b88a557ff89923644
ERROR: Exception:
Traceback (most recent call last):
  File "/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 450, in run
    _, build_failures = build(
  File "/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/site-packages/pip/_internal/wheel_builder.py", line 361, in build
    wheel_cache.record_download_origin(cache_dir, req.download_info)
  File "/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/site-packages/pip/_internal/cache.py", line 282, in record_download_origin
    origin = DirectUrl.from_json(origin_path.read_text())
  File "/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/site-packages/pip/_internal/models/direct_url.py", line 206, in from_json
    return cls.from_dict(json.loads(s))
  File "/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
WARNING: Ignoring invalid distribution -umpy (/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -umpy (/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/site-packages)
Traceback (most recent call last):
  File "/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/bin/pip-sync", line 8, in <module>
    sys.exit(cli())
  File "/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/site-packages/piptools/scripts/sync.py", line 174, in cli
    sync.sync(
  File "/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/site-packages/piptools/sync.py", line 240, in sync
    run(  # nosec
  File "/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/mnt/c/Users/JCPeralta/Documents/Github/unicef-ai4d-poverty-mapping/env/bin/python3.9', '-m', 'pip', 'install', '-r', '/tmp/tmp6y59070e', '--no-binary', 'pygeos,shapely']' returned non-zero exit status 2.
make: *** [Makefile:14: setup] Error 1

**Comment by tm-jace-peralta** [comment]
steps done:
1. ~~deleted and recreated env~~
2. ~~upgrade pygeos to 0.13.0~~

**Comment by tm-jace-peralta** [comment]
solved by removing --no-binary in pygeos line in requirements.txt
